### ISSUE TITLE
upgrade to com.squareup.retrofit2:retrofit:2.2.0

### ISSUE THREAD

**Issue by ejbp** [fikisipi/SmartCache#4]
It seems you're using retrofit2 beta. Please upgrade to com.squareup.retrofit2:retrofit:2.2.0, otherwise it will not work with stable retrofit version.

Thanks

**Comment by dimitrovskif** [comment]
Hi, I upgraded the whole codebase in 8c1045e, and the tests pass.

Would you mind trying
```
dependencies {
    compile 'com.github.dimitrovskif:SmartCache:8c1045e'
}
```
I may release it as SmartCache v0.2 if works well enough.

**Comment by peter1408** [comment]
can i use this above codebase ? or just out of concern !!! when will u be releasing the stable build ????

**Comment by fikisipi** [comment]
@ejbp Upgraded to `2.9.0` :)
