### ISSUE TITLE
Cannot resolve SmartCache on retrofit 2.3.0

### ISSUE THREAD

**Issue by hi-manshu** [fikisipi/SmartCache#5]

**Comment by hi-manshu** [comment]
<img width="708" alt="screen shot 2017-11-16 at 2 38 09 pm" src="https://user-images.githubusercontent.com/13928586/32882911-cca5fa62-cadb-11e7-950d-008556eb3c28.png">

**Comment by fikisipi** [comment]
Added support for 2.9.0, see the README or demo app.

The owner/username of the repo is changed as well.
