### ISSUE TITLE
Provide a sample implementation

### ISSUE THREAD

**Issue by peter1408** [fikisipi/SmartCache#7]
I referred to this sample project of yours [link](https://github.com/dimitrovskif/SmartCache/blob/58d4152a46e668f159c9e6ff0071278f657758e1/demo_app/src/main/java/dimitrovskif/demoapp/MainActivity.java)

but how am I able to check if the value is loaded from the cache before the network response is rendered.. 

how to know if the response is the cache value or a network response???

**Comment by peter1408** [comment]
I figured my own way to test this thing! and you did a great work, working well and smooth! 

I have a concern !!!?? is there any way I can check if the response is from cache or network!

**Comment by dimitrovskif** [comment]
There's no way of checking that; it's a huge problem, I agree.

**Comment by fikisipi** [comment]
@peter1408 I added a function for checking which response is rendered, as well as a function for deleting cache. I added a new demo app as well.

To install the new version change the `implementation` line in Gradle, as mentioned in the README. The demo app is in the base folder as well.
